# action.yml
name: 'gitops action to update gitops template'
description: 'update image in kustomize, commit change to git so cicd tool can pick up'
inputs:
  tag: # id of input
    description: 'Tag version of docker'
    required: true
    default: 'default'
  token:
    description: 'Token for managing github repo'
    required: true
  repo-url:
    description: 'repo url'
    required: true
  message:
    description: 'message '
    required: true
outputs:
  digest:
    description: 'just here for now'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.tag }}
    - ${{ inputs.token }}
    - ${{ inputs.repo-url }}
    - ${{ inputs.message }}
