apiVersion: v1
kind: Service
metadata:
  name: laravelapp-development-elb
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    name: laravelapp-development
